version: '3.9'

services:
  db:
    container_name: cassandra-dev
    image: cassandra
    ports:
      - 9042:9042
    environment:
      CASSANDRA_USE_ASTRA: "false"
      CASSANDRA_USER: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
      CASSANDRA_LOCAL_DC: "datacenter1"
      CASSANDRA_CONTACT_POINTS: "db:9042"
      CASSANDRA_KEYSPACE_CQL: "CREATE KEYSPACE test_keyspace WITH REPLICATION = {'class':'SimpleStrategy','replication_factor':1};"
      MONITORING_PROMETHEUS: "false"
      MONITORING_GRAFANA: "false"
      DISTRIBUTED_TRACING_ENABLED: "false"