name: ci

on: [push]

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml  # use the callable tests job to run tests
  codeql:
    uses: ./.github/workflows/codeql-analysis.yml
  deploy:
    needs:
      - test
      - codeql
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker-compose build