name: test

on: [workflow_call]  # allow this workflow to be called from other workflows

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
    strategy:
      matrix:
        node: ['18']
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Node.js ${{ matrix.node }} (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: run server tests
        # env:
        #   DB_HOST: ${{ secrets.DB_HOST }}
        #   DB_PORT: ${{ secrets.DB_PORT }}
        #   keyspace: ${{ secrets.keyspace }}
        #   strategy: ${{ secrets.strategy }}
        #   DataCenter: ${{ secrets.DataCenter }}
        #   DB_USERNAME: ${{ secrets.DB_USERNAME }}
        #   DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: cd server && npm install

      - name: run client tests
        run: cd client && npm install